### ISSUE TITLE
can not find the module adjustText

### ISSUE THREAD

**Issue by pariswu1988** [mfitzp/padua#3]
hi, now I can install the padua, but when import padua, there is an error said: no module named "adjustText", please give me a hand, thanks!

**Comment by mfitzp** [comment]
Can you check if the adjusttext package is installed? https://github.com/Phlya/adjustText  ...it's in the padua `requirements.txt` but perhaps something was missed during install.

If you're using pip it should just be `pip install adjustText`

Edit: The requirement was missing from setup.py, has been added in latest 0.1.16.

**Comment by pariswu1988** [comment]
yes, problem solved!

**Comment by PyFoundations** [comment]
Uninstall adjustText and pip install it with the argument --no-cache-dir worked for me.
$pip uninstall adjustText
$pip install --no-cache-dir adjustText
